// Generated by CoffeeScript 1.8.0
(function() {
  var Client, assert;

  Client = (require('../lib/yapople')).Client;

  assert = require('assert');

  describe('POP3 client tests', function() {
    var options, tlsOptions;
    options = {
      hostname: process.env.HOSTNAME ? process.env.HOSTNAME : 'pop.mail.ru',
      port: process.env.PORT ? parseInt(process.env.PORT) : 110,
      username: 'yapople',
      password: 'yapopleyapopleyapopleyapople'
    };
    tlsOptions = {
      hostname: process.env.HOSTNAME ? process.env.HOSTNAME : 'pop.mail.ru',
      port: process.env.PORT ? parseInt(process.env.PORT) : 995,
      tls: true,
      username: 'yapople',
      password: 'yapopleyapopleyapopleyapople'
    };
    describe('connect', function() {
      it('should connect to the existing server', function(done) {
        var client;
        client = new Client(options);
        return client.connect(function(err, data) {
          assert.equal(err, null);
          client.disconnect();
          return done();
        });
      });
      this.timeout(50000);
      it('should not login to TLS server without tls option', function(done) {
        var client;
        client = new Client(options);
        return client.connect(function(err, data) {
          assert.equal(err, null);
          return client.login(function(err, data) {
            assert.notEqual(err, null);
            assert.equal(err, 'POP3 is available only with SSL or TLS connection enabled');
            client.disconnect();
            return done();
          });
        });
      });
      return it('should login to TLS server with tls option', function(done) {
        var client;
        client = new Client(tlsOptions);
        return client.connect(function(err, data) {
          assert.equal(err, null);
          return client.login(function(err, data) {
            assert.equal(err, null);
            assert.equal(data, 'Welcome!');
            client.disconnect();
            return done();
          });
        });
      });
    });
    describe('stat command', function() {
      return it('return message count', function(done) {
        var client;
        client = new Client(tlsOptions);
        client.debug = true;
        return client.connect(function(err, data) {
          assert.equal(err, null);
          return client.login(function(err, data) {
            assert.equal(err, null);
            return client.stat(function(err, data) {
              assert.equal(err, null);
              console.log(data);
              client.disconnect();
              return done();
            });
          });
        });
      });
    });
    return describe('list command', function() {
      return it('return message count', function(done) {
        var client;
        client = new Client(tlsOptions);
        client.debug = true;
        return client.connect(function(err, data) {
          assert.equal(err, null);
          return client.login(function(err, data) {
            assert.equal(err, null);
            return client.list(function(err, data) {
              assert.equal(err, null);
              console.log(data);
              client.disconnect();
              return done();
            });
          });
        });
      });
    });
  });

}).call(this);

//# sourceMappingURL=main.js.map
