// Generated by CoffeeScript 1.7.1
(function() {
  var Client, assert, nodemailer;

  Client = (require('../lib/yapople')).Client;

  assert = require('assert');

  nodemailer = require('nodemailer');

  describe('POP3 client tests', function() {
    var options, tlsOptions;
    this.timeout(20000);
    before(function(done) {
      var mailOptions, transporter;
      return done();
      transporter = nodemailer.createTransport({
        service: 'Mail.ru',
        auth: {
          user: 'yapople@mail.ru',
          pass: 'yapopleyapopleyapopleyapople'
        }
      });
      mailOptions = {
        from: 'yapople@mail.ru',
        to: 'yapople@mail.ru',
        subject: 'Hello ✔',
        text: 'Hello world ✔',
        html: '<b>Hello world ✔</b>'
      };
      return transporter.sendMail(mailOptions, function(error, info) {
        if (error) {
          return console.log(error);
        } else {
          return done();
        }
      });
    });
    options = {
      hostname: 'pop.mail.ru',
      port: 110,
      username: 'yapople',
      password: 'yapopleyapopleyapopleyapople'
    };
    tlsOptions = {
      hostname: 'pop.mail.ru',
      port: 995,
      tls: true,
      username: 'yapople',
      password: 'yapopleyapopleyapopleyapople'
    };
    describe('connect', function() {
      it('should connect to the existing server', function(done) {
        var client;
        client = new Client(options);
        return client.connect(function(err, data) {
          assert.equal(err, null);
          client.disconnect();
          return done();
        });
      });
      it('should not login to TLS server without tls option', function(done) {
        var client;
        client = new Client(options);
        return client.connect(function(err, data) {
          assert.equal(err, null);
          return client.login(function(err, data) {
            assert.notEqual(err, null);
            assert.equal(err, 'POP3 is available only with SSL or TLS connection enabled');
            client.disconnect();
            return done();
          });
        });
      });
      return it('should login to TLS server with tls option', function(done) {
        var client;
        client = new Client(tlsOptions);
        return client.connect(function(err, data) {
          assert.equal(err, null);
          return client.login(function(err, data) {
            assert.equal(err, null);
            assert.equal(data, 'Welcome!');
            client.disconnect();
            return done();
          });
        });
      });
    });
    describe('stat command', function() {
      return it('returns message stat count', function(done) {
        var client;
        client = new Client(tlsOptions);
        return client.connect(function(err, data) {
          assert.equal(err, null);
          return client.login(function(err, data) {
            assert.equal(err, null);
            return client.stat(function(err, data) {
              assert.equal(err, null);
              client.disconnect();
              return done();
            });
          });
        });
      });
    });
    describe('list command', function() {
      it('returns message list count', function(done) {
        var client;
        client = new Client(tlsOptions);
        return client.connect(function(err, data) {
          assert.equal(err, null);
          return client.login(function(err, data) {
            assert.equal(err, null);
            return client.list(function(err, data) {
              assert.equal(err, null);
              client.disconnect();
              return done();
            });
          });
        });
      });
      return it('returns info about message', function(done) {
        var client;
        client = new Client(tlsOptions);
        return client.connect(function(err, data) {
          assert.equal(err, null);
          return client.login(function(err, data) {
            assert.equal(err, null);
            return client.list(1, function(err, data) {
              assert.equal(err, null);
              client.disconnect();
              return done();
            });
          });
        });
      });
    });
    describe('retr command', function() {
      it('should return message body for known message', function(done) {
        var client;
        client = new Client(tlsOptions);
        return client.connect(function(err, data) {
          assert.equal(err, null);
          return client.login(function(err, data) {
            assert.equal(err, null);
            return client.retr(1, function(err, data) {
              assert.equal(err, null);
              client.disconnect();
              return done();
            });
          });
        });
      });
      return it('should return an error for unknown message', function(done) {
        var client;
        client = new Client(tlsOptions);
        return client.connect(function(err, data) {
          assert.equal(err, null);
          return client.login(function(err, data) {
            assert.equal(err, null);
            return client.retr(666, function(err, data) {
              assert.notEqual(err, null);
              client.disconnect();
              return done();
            });
          });
        });
      });
    });
    describe('retr command', function() {
      return it('should return parsed message when using mailparser', function(done) {
        var client;
        tlsOptions.mailparser = true;
        client = new Client(tlsOptions);
        return client.connect(function(err, data) {
          assert.equal(err, null);
          return client.login(function(err, data) {
            assert.equal(err, null);
            return client.retr(1, function(err, data) {
              assert.equal(err, null);
              assert.ok(data.text);
              if (!data.subject) {
                console.log(data);
              }
              assert.ok(data.subject);
              assert.ok(data.headers);
              client.disconnect();
              return done();
            });
          });
        });
      });
    });
    return describe('count command', function() {
      return it('should return message count', function(done) {
        var client;
        client = new Client(tlsOptions);
        return client.connect(function(err, data) {
          assert.equal(err, null);
          return client.login(function(err, data) {
            assert.equal(err, null);
            return client.count(function(err, data) {
              assert.equal(err, null);
              assert.ok(data >= 0);
              client.disconnect();
              return done();
            });
          });
        });
      });
    });
  });

}).call(this);

//# sourceMappingURL=main.map
